[package]
name = "krust"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[workspace]

[dependencies]
blake3 = { version = "1.8.3", default-features = false, features = ["pure"] }

[profile.dev]
panic = "abort"

[profile.dev.package.blake3]
opt-level = 3

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
strip = "debuginfo"
