timeout: 0
serial: yes

/Krust
    protocol: limine
    path: boot():/boot/krust.elf
    module_path: boot():/boot/hello-generation.vertex.json
    module_string: vertex-manifest
    module_path: boot():/boot/krust-ipc-sender.elf
    module_string: krust-ipc-sender
    module_path: boot():/boot/krust-ipc-receiver.elf
    module_string: krust-ipc-receiver
