timeout: 0
serial: yes

/Krust
    protocol: limine
    path: boot():/boot/krust.elf
    module_path: boot():/boot/hello-generation.krustboot
    module_string: krustboot-manifest
    module_path: boot():/boot/fallback-generation.krustboot
    module_string: krustboot-fallback-manifest
    module_path: boot():/boot/bad-generation.krustboot
    module_string: krustboot-bad-generation-manifest
    module_path: boot():/boot/vertex-init.elf
    module_string: vertex-init
    module_path: boot():/boot/serial-driver.elf
    module_string: serial-driver
    module_path: boot():/boot/logd.elf
    module_string: logd
    module_path: boot():/boot/echo.elf
    module_string: echo
    module_path: boot():/boot/netstack.elf
    module_string: netstack
    module_path: boot():/boot/block-driver.elf
    module_string: block-driver
    module_path: boot():/boot/vertex-store.elf
    module_string: vertex-store
    module_path: boot():/boot/vertex-state.elf
    module_string: vertex-state
    module_path: boot():/boot/vertex-inspect.elf
    module_string: vertex-inspect
    module_path: boot():/boot/model-reader.elf
    module_string: model-reader
    module_path: boot():/boot/counter.elf
    module_string: counter
    module_path: boot():/boot/state-reader.elf
    module_string: state-reader
    module_path: boot():/boot/timer.elf
    module_string: timer
    module_path: boot():/boot/flaky.elf
    module_string: flaky
    module_path: boot():/boot/hog.elf
    module_string: hog
    module_path: boot():/boot/faulty.elf
    module_string: faulty
    module_path: boot():/boot/hello-text.txt
    module_string: store-hello-text
