timeout: 0
serial: yes

/Krust
    protocol: limine
    path: boot():/boot/krust.elf
    module_path: boot():/boot/hello-generation.krustboot
    module_string: krustboot-manifest
    module_path: boot():/boot/fallback-generation.krustboot
    module_string: krustboot-fallback-manifest
    module_path: boot():/boot/bad-generation.krustboot
    module_string: krustboot-bad-generation-manifest
    module_path: boot():/boot/krust-block.img
    module_string: vertexdisk-store
