OUTPUT_FORMAT(elf64-x86-64)
OUTPUT_ARCH(i386:x86-64)
ENTRY(_start)

PHDRS
{
    text PT_LOAD FLAGS(5);
    rodata PT_LOAD FLAGS(4);
    data PT_LOAD FLAGS(6);
}

SECTIONS
{
    . = 0x0000000000400000;

    . = ALIGN(4K);
    .text :
    {
        KEEP(*(.text._start))
        *(.text .text.*)
    } :text

    . = ALIGN(4K);
    .rodata :
    {
        *(.rodata .rodata.*)
        *(.eh_frame_hdr)
        *(.eh_frame .eh_frame.*)
    } :rodata

    . = ALIGN(4K);
    .data :
    {
        *(.data .data.*)
        *(.sdata .sdata.*)
        *(.got .got.*)
    } :data

    . = ALIGN(4K);
    .bss :
    {
        *(COMMON)
        *(.bss .bss.*)
        *(.sbss .sbss.*)
    } :data

    /DISCARD/ :
    {
        *(.note .note.*)
        *(.comment .comment.*)
    }
}
